services:
  tao_pyt:
    image: nvcr.io/nvidia/tao/tao-toolkit:6.25.10-pyt
    container_name: tao_pyt
    runtime: nvidia
    shm_size: 8gb
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./apps/:/apps  
    # === EQUIVALENTE a docker run -it ===
    stdin_open: true
    tty: true
